/**
 * Segments-screen sample rows.
 * Small fixed sample the client-side filters against for the table body.
 * Real matchCount is a demo fixture in segments-fixture.ts.
 */

export interface SegmentSampleRow {
  id: string;
  name: string;
  role: string;
  employer: string;
  industry: string;
  city: string;
  state: string;
  sydneyMetro: boolean;
  study: 'cs' | 'eng' | 'commerce' | 'any';
  grad: number;
  signals: Array<'promoted' | 'moved' | 'role-change' | 'course-gap' | 'redundancy' | 'industry-change'>;
  event: string;
  when: string;
  lastCourse: string; // "MMM YYYY"
  consent: string;
  score: number;
}

const CURRENT_YEAR = new Date().getFullYear();
const yearsAgo = (n: number) => `${['Jan', 'Mar', 'Jun', 'Sep', 'Nov'][n % 5]} ${CURRENT_YEAR - n}`;

export const SEGMENTS_SAMPLE: SegmentSampleRow[] = [
  {
    id: 'a-01',
    name: 'Priya Nair',
    role: 'Head of Data Engineering',
    employer: 'Atlassian',
    industry: 'Technology',
    city: 'Melbourne',
    state: 'VIC',
    sydneyMetro: false,
    study: 'cs',
    grad: 2013,
    signals: ['promoted'],
    event: 'Promoted 6 weeks ago',
    when: '6w ago',
    lastCourse: yearsAgo(5),
    consent: 'Email + SMS',
    score: 0.912,
  },
  {
    id: 'a-02',
    name: 'James O’Connor',
    role: 'Senior Platform Engineer',
    employer: 'Canva',
    industry: 'Technology',
    city: 'Brisbane',
    state: 'QLD',
    sydneyMetro: false,
    study: 'cs',
    grad: 2015,
    signals: ['promoted', 'moved'],
    event: 'Moved from Sydney to Brisbane',
    when: '4m ago',
    lastCourse: yearsAgo(4),
    consent: 'Email',
    score: 0.887,
  },
  {
    id: 'a-03',
    name: 'Wei Chen',
    role: 'Engineering Manager',
    employer: 'Commonwealth Bank',
    industry: 'Financial Services',
    city: 'Melbourne',
    state: 'VIC',
    sydneyMetro: false,
    study: 'cs',
    grad: 2011,
    signals: ['promoted'],
    event: 'Promoted to EM',
    when: '3m ago',
    lastCourse: yearsAgo(6),
    consent: 'Email + SMS',
    score: 0.874,
  },
  {
    id: 'a-04',
    name: 'Aisha Rahman',
    role: 'Lead Data Scientist',
    employer: 'Xero',
    industry: 'Technology',
    city: 'Newcastle',
    state: 'NSW',
    sydneyMetro: false,
    study: 'cs',
    grad: 2014,
    signals: ['promoted'],
    event: 'Promoted 8 weeks ago',
    when: '8w ago',
    lastCourse: yearsAgo(3),
    consent: 'Email + SMS',
    score: 0.851,
  },
  {
    id: 'a-05',
    name: 'Tom Whitfield',
    role: 'Principal Software Engineer',
    employer: 'Culture Amp',
    industry: 'Technology',
    city: 'Melbourne',
    state: 'VIC',
    sydneyMetro: false,
    study: 'cs',
    grad: 2012,
    signals: ['promoted', 'course-gap'],
    event: 'Promoted, no course in 5y',
    when: '2m ago',
    lastCourse: yearsAgo(5),
    consent: 'Email',
    score: 0.838,
  },
  {
    id: 'a-06',
    name: 'Zoe Ferguson',
    role: 'Head of Engineering',
    employer: 'Freelancer.com',
    industry: 'Technology',
    city: 'Perth',
    state: 'WA',
    sydneyMetro: false,
    study: 'cs',
    grad: 2010,
    signals: ['promoted'],
    event: 'Promoted to Head of',
    when: '5m ago',
    lastCourse: yearsAgo(7),
    consent: 'Email + SMS',
    score: 0.822,
  },
  {
    id: 'a-07',
    name: 'Rahim Ahmed',
    role: 'Staff Engineer',
    employer: 'Google',
    industry: 'Technology',
    city: 'Melbourne',
    state: 'VIC',
    sydneyMetro: false,
    study: 'cs',
    grad: 2013,
    signals: ['promoted'],
    event: 'Promoted to Staff',
    when: '9w ago',
    lastCourse: yearsAgo(4),
    consent: 'Email',
    score: 0.809,
  },
  {
    id: 'a-08',
    name: 'Laura Kingsley',
    role: 'Engineering Director',
    employer: 'Zip Co',
    industry: 'Financial Services',
    city: 'Newcastle',
    state: 'NSW',
    sydneyMetro: false,
    study: 'cs',
    grad: 2009,
    signals: ['promoted', 'industry-change'],
    event: 'Promoted to Director',
    when: '11w ago',
    lastCourse: yearsAgo(6),
    consent: 'Email + SMS',
    score: 0.798,
  },
  {
    id: 'a-09',
    name: 'Ben Ross',
    role: 'Senior Backend Engineer',
    employer: 'REA Group',
    industry: 'Technology',
    city: 'Melbourne',
    state: 'VIC',
    sydneyMetro: false,
    study: 'eng',
    grad: 2016,
    signals: ['role-change'],
    event: 'New role at REA',
    when: '3m ago',
    lastCourse: yearsAgo(2),
    consent: 'Email',
    score: 0.762,
  },
  {
    id: 'a-10',
    name: 'Meera Patel',
    role: 'Product Manager',
    employer: 'Deputy',
    industry: 'Technology',
    city: 'Adelaide',
    state: 'SA',
    sydneyMetro: false,
    study: 'commerce',
    grad: 2015,
    signals: ['promoted'],
    event: 'Promoted to PM',
    when: '4m ago',
    lastCourse: yearsAgo(4),
    consent: 'Email + SMS',
    score: 0.748,
  },
  {
    id: 'a-11',
    name: 'Sarah Nguyen',
    role: 'Data Analyst',
    employer: 'Ansell',
    industry: 'Manufacturing',
    city: 'Wollongong',
    state: 'NSW',
    sydneyMetro: false,
    study: 'cs',
    grad: 2018,
    signals: ['course-gap'],
    event: 'No course in 3y',
    when: '—',
    lastCourse: yearsAgo(3),
    consent: 'Email',
    score: 0.712,
  },
  {
    id: 'a-12',
    name: 'Marcus Cole',
    role: 'DevOps Lead',
    employer: 'NAB',
    industry: 'Financial Services',
    city: 'Melbourne',
    state: 'VIC',
    sydneyMetro: false,
    study: 'cs',
    grad: 2012,
    signals: ['promoted'],
    event: 'Promoted to Lead',
    when: '5m ago',
    lastCourse: yearsAgo(5),
    consent: 'Email + SMS',
    score: 0.694,
  },
  {
    id: 'a-13',
    name: 'Emma Sinclair',
    role: 'Senior Software Engineer',
    employer: 'Culture Amp',
    industry: 'Technology',
    city: 'Sydney',
    state: 'NSW',
    sydneyMetro: true,
    study: 'cs',
    grad: 2016,
    signals: ['promoted'],
    event: 'Promoted (Sydney-based)',
    when: '2m ago',
    lastCourse: yearsAgo(4),
    consent: 'Email',
    score: 0.671,
  },
  {
    id: 'a-14',
    name: 'Daniel Park',
    role: 'Engineering Manager',
    employer: 'MYOB',
    industry: 'Technology',
    city: 'Melbourne',
    state: 'VIC',
    sydneyMetro: false,
    study: 'cs',
    grad: 2011,
    signals: ['promoted', 'course-gap'],
    event: 'Promoted, 6y course gap',
    when: '6m ago',
    lastCourse: yearsAgo(6),
    consent: 'Email + SMS',
    score: 0.648,
  },
];
